[package]
name = "csf-frontend"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
axum = { workspace = true }
dioxus = { workspace = true }
dioxus-ssr = { workspace = true }
tokio = { workspace = true, features = ["full"] }
