version: '3'

networks:
  network:

services:
  postgres:
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - network
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - POSTGRES_DB=coin_sight
    ports:
      - 5432:5432