name: Build and push Docker images
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: graphql
            dockerfile: ./Dockerfile
          - target: chainlink-collector
            dockerfile: ./Dockerfile
          - target: coingecko-collector
            dockerfile: ./Dockerfile
          - target: cryptocompare-collector
            dockerfile: ./Dockerfile
          - target: gateio-collector
            dockerfile: ./Dockerfile
          - target: aggregator
            dockerfile: ./Dockerfile
          - target: user-service
            dockerfile: ./Dockerfile
          - target: notification-service
            dockerfile: ./Dockerfile
          - target: telegram-notification
            dockerfile: ./Dockerfile
          - target: frontend
            dockerfile: ./frontend/Dockerfile

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (push)
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.target }}:${{ github.sha }}

      - name: Build image (pull request)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
